# -*- coding: utf-8 -*-
"""Pandas_Profiling_Report.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BbAStiZgNJrZTXFjOyE6SbAR61kF7tVj
"""



from google.colab import drive
drive.mount('/content/drive')

pip install pandas-profiling

pip install pandas

#Importing Pandas as pd
import pandas as pd

#Here we connect the data from our library and store it in a veriable path
path="/content/drive/MyDrive/business-operations-survey-2022-price-and-wage-setting.csv"
df=pd.read_csv(path,encoding='cp1252')
df.head(10)

#Here we reading all the data in a file
df=pd.read_csv(path,encoding='cp1252')
df

#Here we import PofileReport from Pandas-Profiling(Also known as ydata_profiling) and making a report with the name of "first_Report".
from ydata_profiling import ProfileReport
prof=ProfileReport(df)
prof.to_file(output_file="first_Report.html")

#Here we are making small report name of "Small_Report".
prof=ProfileReport(df, minimal=True )
prof.to_file(output_file="Small_Report.html")

